name: Tweet

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * *"
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Npm Install
        uses: bahmutov/npm-install@v1.6.0
      - name: Tweet
        run: npm run tweet
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
